# ruff.toml
target-version = "py310"
line-length = 120

[lint]
select = ["E", "F", "W", "I", "UP", "ANN"]
ignore = ["E501", "ANN001", "ANN002", "ANN003", "ANN201", "ANN401"]

[lint.isort]
combine-as-imports = true
known-first-party = ["exporter_base", "libs"]

[format]
quote-style = "double"
indent-style = "space"
