FROM python:3.11-slim

RUN pip install uv
WORKDIR /app

RUN uv pip install --system --no-cache \
    redis \
    orjson \
    faker \
    pyyaml

COPY scripts/staging_seeder.py .
COPY helm/aragog-exporters/values.yaml ./helm/aragog-exporters/values.yaml

CMD ["python", "-u", "staging_seeder.py"]
