# ArgoCD: https://argocd.dev.rea/applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aragog-exporters-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gorealytics-com/aragog-exporters.git
    targetRevision: develop
    path: helm/aragog-exporters
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aragog-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
